name: dev-lista-arquivos

services:
  app:
    image: node:20.15.1-slim
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8001:8001
    volumes:
      - ..:/app
    working_dir: /app
    command: /bin/sh -c '
      yarn
      && yarn dev
      '
    #command: /bin/sh -c 'tail -f /dev/null'

